#!/bin/bash

podman build -t --network podman helloworld .
podman run -p 3004:3004 helloworld

echo "=========================================="
echo "Podman NodeJS TestInstallation"
echo "Environment: Development"
echo "Container Runtime: Podman"
echo "=========================================="
